name: mobile_test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/json/drink_json.json
    - assets/json/option_json.json
    - assets/json/size_json.json
    - assets/json/topping_json.json

